Deep Wide Selu Neural Network
riceluxs1t/KBOPrediction pull request #1
Opened 2017-06-20 02:11 UTC by bluejay9676

and indices
- Added Tensorflow NN model
- General parameters to run the model.
- Needs the data to format the input.
- Need to freeze the learned weights (will have to search that up)

2017-06-20 02:37 UTC, riceluxs1t commented on index.py
> +## NN paramters
여기 정의 된 상수들 constants.py 로 옮기는게 어떨까

2017-06-20 02:37 UTC, riceluxs1t commented on index.py
> +keep_rate = 0.7
그리고 주로 상수값들은 대문자로 LEARNING_RATE 이렇게 하는게 convention

2017-06-20 02:37 UTC, riceluxs1t commented on NN.py
> +
마이너한 nit 인데 주로 같은 파일에서 불러온 함수들은 같은 라인에 적는게 좋아.
from tensorflow.python.ops import math_ops, random_ops, array_ops

또한, import 순서는 주로 외부 3rd party module 들을 alphanumerical 한 순서대로
그리고 한줄 띄우고 내부 module 들 alphanumerical 한 순서대로 정렬함.

2017-06-20 02:37 UTC, riceluxs1t commented on NN.py
> +tf.set_random_seed(777)  # reproducibility
run 을 하는 runner 같은애를 따로 분리해서 걔가 이런 값들을 실행하도록 하는게 좋을듯

2017-06-20 02:37 UTC, riceluxs1t commented on NN.py
> +    """Dropout to a value with rescaling."""
def dropout_selu(
     x,
     keep_prob,
     alpha=....
) 
로 정리

2017-06-20 02:37 UTC, riceluxs1t commented on NN.py
> +    """Dropout to a value with rescaling."""
x, keep_prob, alpha 앞에 탭 넣어서

2017-06-20 02:37 UTC, riceluxs1t commented on NN.py
> +# DATA
이 아래 실행하는 파트들도 들도 다 runner 같은거로 분리.

2017-06-20 02:37 UTC, riceluxs1t commented on index.py
> +keep_rate = 0.7
그리고 파일 이름은 NN.py 보다 model.py 로

2017-06-20 03:23 UTC, bluejay9676 commented
- Runner & Model separated
- Parameters in index.py -> constants.py
- Fixed according to the coding convention

2017-06-23 06:21 UTC, bluejay9676 commented
Accuracy of 73% model

2017-06-29 01:55 UTC, riceluxs1t requested changes

2017-06-29 01:55 UTC, riceluxs1t commented on runner.py
> +"""
this file is just written vey terribly.
1) the way it is written, the expensive modeling part is executed every single time this file is imported. 
2) Some hyper parameters  that determine which data to use, what to name the output file, should all be input from the user.

Solutions,
1) wrap the executable part in 

if __name__ == '__main__':

code block,
this ensures that all the lines (not wrapped in functions, classes) are only run when you run something like python runner.py ......arguments.... from your terminal

2) AVOID HARD CODING. engineering principle 101. have them be input from the user instead. the standard thing to use here is to use python's builtin argparse module. This wraps stuff around the vanilla input(), raw_input() stuff and makes your life easier to write python executables. example code https://gist.github.com/riceluxs1t/60cb8509d9dc7bcecacf335120e3386c

2017-06-29 01:55 UTC, riceluxs1t commented on constants.py
> +## NN paramters
Have all these be user input.

2017-06-29 01:55 UTC, riceluxs1t commented on model.py
> +        alpha = 1.6732632423543772848170429916717
these should be constants.

2017-07-18 20:30 UTC, closed without merging